
services:
  # los servicios db y adminer se implementaron tomando
  # como referencia al ejemplo compose.yaml de https://hub.docker.com/_/postgres

  db:
    image: postgres:18-alpine3.22
    restart: always
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128MB
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: imagoDB

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_DRIVER: pgsql
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DEFAULT_DB: imagoDB
      ADMINER_DESIGN: dark
    volumes:
      - ./adminer/designs/adminer-dark.css:/var/www/html/designs/dark/adminer.css

  api:
    depends_on:
      - db
    build: ./api/
    ports:
      - "3000:3000"
