
services:
  # los servicios db y adminer se implementaron tomando
  # como referencia al ejemplo compose.yaml de https://hub.docker.com/_/postgres

  db:
    image: postgres:18-alpine3.22
    restart: always
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:Z
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128MB
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: imagoDB
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d imagoDB" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_DRIVER: pgsql
      ADMINER_DEFAULT_SERVER: db
      ADMINER_DEFAULT_DB: imagoDB
      ADMINER_DESIGN: dark
    volumes:
      - ./adminer/designs/adminer-dark.css:/var/www/html/designs/dark/adminer.css:Z

  api:
    depends_on:
      - db
    build: ./api/
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_USERNAME: "admin"
      DATABASE_PASSWORD: "1234"
      DATABASE_DATABASE: "imagoDB"
      DATABASE_HOST: "db"
      DATABASE_PORT: "5432"
      NODE_ENV: "development"
      PORT: "3000"

  front:
    depends_on:
      - api
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./front:/usr/share/nginx/html:ro,Z
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro,Z
